### ISSUE TITLE
Allow user to set CONNECT_API_SERVER

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#103]
part of

* #93

**Comment by juliasilge** [comment]
Yes, I believe it is `CONNECT_SERVER` (that's what is in my env variables). 👍

**Comment by machow** [comment]
Looks like `board_rsconnect` started reading the CONNECT_SERVER variable at some point..!

https://github.com/rstudio/pins-python/blob/main/pins/constructors.py#L395
