### ISSUE TITLE
add quick example to the README, move dev instructions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#113]
We should use a format like README.Rmd that can run any code in it, and generate the final README. See https://github.com/machow/dbcooper-py for an example. (Note that we could use basically any jupytext format, etc..)

https://github.com/rstudio/pins#usage

<img width="907" alt="image" src="https://user-images.githubusercontent.com/2574498/166947455-89bd26e9-6785-46d3-8123-73984a0df983.png">

**Comment by juliasilge** [comment]
I was thinking about the README lately in general. Right now, it seems very developer focused ("I wanted to contribute to this package") and not so user focused ("I want to use this package"). We generally find that most people who come to our repos on GH are looking to use the package, not contribute to it. What would you think about revamping the README quite a bit, with a focus on the user audience, and moving contributing-specific info to a `CONTRIBUTING.md`?

**Comment by machow** [comment]
That seems great! I'll update title to reflect that piece
