### ISSUE TITLE
RSC: ensure python pins (at the least) matches R pins in terms the size files it can upload

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#129]
From pairing w/ Gagan -- when he attempted to pin a file that was ~ 2 gigabytes it led to a connection timeout error. The error occurred while pins was attempting to POST a new bundle. This is the point where it uploads the file.

**Comment by machow** [comment]
I'm not able to replicate Gagan's Connection timed out error, but am able to get both libraries to fail for a file of the same size (2.2 Gb). The big challenge is that formats like Rds are compressed, so I used a CSV to ensure they sent roughly the same payload.

They both get `413 Client Error: Request Entity Too Large for url`

**Generate data in R**

```R
library(tidyverse)
library(readr)

set.seed(123)

df <- tibble(x = rnorm(120000000))
df %>% write_csv("test.csv")
```

**Attempt upload**

R

```R
library(pins)
library(tidyverse)

board <- board_rsconnect(server = "colorado.rstudio.com")

board %>% pin_write(read_csv("test.csv"), "test-large-pin", type="csv")
```

python

```python
from pins import board_rsconnect
from dotenv import load_dotenv
load_dotenv(override=True)
board = board_rsconnect("https://colorado.rstudio.com/rsc", allow_pickle_read=True)

df = pd.read_csv("test.csv")
board.pin_write(df, "test-large-pin", type="csv")

# note, also ran df.to_csv("test2.csv"), to ensure it dumps as same size
```

## What could cause the connection to time out?

* maybe the file was within RSC limits (what are those?), but just big enough to cause a timeout?
* maybe the small container memory (2Gb) / CPU caused the uploads to be very slow?

**Comment by juliasilge** [comment]
OK, this definitely sounds like a Connect issue, not anything to do with pins. It will be good to offer any support or ideas we can, but it sounds like we have confirmed (like we expected) that this is not related to pins. Thank you for helping on this! 🙌

**Comment by gsingh91** [comment]
I talked with Kelly and Cole about this, and it looks like an issue with the nginx proxy in front of Colorado. Since this is an architectural decision, maybe we can add a message on the pins side that if this error occurs, the user should check with their admins about proxies and their limits?

**Comment by gsingh91** [comment]
An older thread for the same issue with R pins: https://rstudio.slack.com/archives/CH772PS75/p1604525555022700

**Comment by juliasilge** [comment]
Hmmmm, we can look into how robust it could be to capture this particular error, but I'm not sure it will be possible or sensible from a maintenance and/or design perspective for the pins package to handle errors from a load balancer, for example.

**Comment by machow** [comment]
It seems like load balancer issues will manifest in various ways across RSC, so we may want to send people to an RSC specific page. I'm going to close for now, but happy to reopen if there's a way for pins to make things easier here...!
