### ISSUE TITLE
Description of board_gcs is incorrect

### ISSUE THREAD

**Issue by robinsones** [rstudio/pins-python#140]
The description of `board_gcs` is: 
https://github.com/rstudio/pins-python/blob/20bd96292989f43f3dd146be212fa5e579e4526b/pins/constructors.py#L390-L391

While it should be "Create a board to read and write pins from a Google Cloud Storage bucket"

If it's helpful I can make a PR with the change, though I'm not familiar in Python vs R what steps if any need to be run to propagate a change in documentation in that file.

**Comment by machow** [comment]
Ah thanks! I can tuck it into some other quick doc fixes  tomorrow when I merge https://github.com/rstudio/pins-python/pull/137

**Comment by machow** [comment]
Should be fixed / released! https://github.com/rstudio/pins-python/pull/137

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/2574498/175654380-bc84936e-cdfd-4c7a-851c-acdb242a45a4.png">
