### ISSUE TITLE
Are the different options for `pin_write(type=...)` documented anywhere?

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/pins-python#144]
Are the supported types documented anywhere? When looking through the docs I could not find anything.

https://github.com/rstudio/pins-python/blob/8915c12dde9d72a302bae7f9d5575756beaf6fb9/pins/boards.py#L240-L241

<https://rstudio.github.io/pins-python/api/api_card/pins.boards.BaseBoard.pin_write.html>

<img width="981" alt="Screen Shot 2022-06-29 at 8 47 50 AM" src="https://user-images.githubusercontent.com/18248949/176480038-7c629b8b-6a95-4bfd-a807-50176679dac7.png">

**Comment by juliasilge** [comment]
It looks like the Getting Started also needs to be updated in this section:
https://rstudio.github.io/pins-python/getting_started.html#reading-and-writing-data

**Comment by machow** [comment]
Thanks for flagging!

Added a list of types to the docstring, to provide similar documentation as R pins :

**R pins**

![image](https://user-images.githubusercontent.com/2574498/189966953-d39219b1-88f2-4823-a647-dba8e2b962b3.png)

**Python pins**

![image](https://user-images.githubusercontent.com/2574498/189967187-d71835d6-d544-4731-ae0f-f97b3237fb9e.png)
