### ISSUE TITLE
Add optional url field to _BaseVersion

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#154]
Currently, R pins adds a url field to the meta$local result of `pin_meta` for these boards:

* board_rsconnect
* board_url

Let's add an optional URL field high up in the version hierarchy, so that boards can tack it on as supplemental info. This is used by vetiver R in its rapidoc API spec.

**Comment by isabelizimm** [comment]
When the url is added (probably in a `local` data structure like R), can we add the GUID? R currently stores this as well. And, as a plus, it would get https://github.com/rstudio/vetiver-python/issues/96 nearly solved 😄

**Comment by machow** [comment]
Some examples:

S3:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/2574498/199284057-f6176052-1755-465b-9e58-3c38b86cff9e.png">


RSC:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/2574498/199284195-19903588-18e1-4ea3-8af8-044b0780961d.png">

**Comment by isabelizimm** [comment]
possibility to use [lru cache](https://docs.python.org/3/library/functools.html) to achieve this? rather than `_user_name_cache`

**Comment by isabelizimm** [comment]
implemented in #167
