### ISSUE TITLE
Raise informative error if user does not pass name to pin_write

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#158]
Currently the `.pin_write()` method lets `name=` be optional. However, this argument is actually necessary. Let's either make this a positional argument, or give a very friendly message.

**Comment by isabelizimm** [comment]
closing out! users get the following error:

```
ValueError: Invalid pin name: mtcars
RStudio Connect pin names must include user name. E.g. 
some_user/mtcars, for the user some_user.
```
