### ISSUE TITLE
Rename `board_urls()` to `board_url()`

### ISSUE THREAD

**Issue by juliasilge** [rstudio/pins-python#160]
The R package has the URL board [as `board_url()`](https://pins.rstudio.com/reference/board_url.html) and the plural here was a bit of an oversight, so let's harmonize these names eventually. Related to rstudio/pins-r#650.

**Comment by machow** [comment]
I think this may be completed already. Using `board_urls` gives a deprecation warning in pins-python, encouraging the use of `board_url`. Do you mind double checking and closing / letting me know if more is needed?

https://github.com/rstudio/pins-python/blob/main/pins/constructors.py#L298-L309

**Comment by machow** [comment]
I think the switch to `board_url` was done in the reference (but wouldn't be surprised if there are lingering board_urls references)

<img width="840" alt="image" src="https://user-images.githubusercontent.com/2574498/198329179-6c573611-22c7-46b4-b4df-d0fe34a18184.png">

**Comment by juliasilge** [comment]
Ah yep, you [did this last month](https://github.com/rstudio/pins-python/commit/99ad308f3dd61bd3bb64173d86e5e4b6a0becb37). Apologies for not looking carefully enough! 🙌
