### ISSUE TITLE
Implement `board_url()`

### ISSUE THREAD

**Issue by juliasilge** [rstudio/pins-python#163]
The main value of `board_url()` is automatic caching for web resources. 

More speculatively, maybe people would eventually like to use the workflow we are developing for pins in R: write an object to something like `board_s3()`, make the S3 bucket available to everyone who should have it, and then read with `board_url()` (no authentication). This would involve more features, though, like a manifest.

**Comment by machow** [comment]
`board_url` is implemented (here is its [api doc page](https://rstudio.github.io/pins-python/api/api_card/pins.board_url.html#pins.board_url)).

I'm noticing the getting started page of the docs has a section saying its unimplemented. I'll go through the docs and remove anything that sounds like it's unimplemented!

**Comment by machow** [comment]
Should be resolved in https://github.com/rstudio/pins-python/pull/169
