### ISSUE TITLE
typo, line 305, `./pins/boards.py` missing f for f-string

### ISSUE THREAD

**Issue by hhp94** [rstudio/pins-python#170]
pins version: 0.7.1
python: 3.9.13
os: Ubuntu 22.04 LTS

Thank you so much for your hard work on Pins. I'm so excited about this project. Now I can use `{mice}` and `{missForest}` for imputation and my coworkers can run their models using my data in Python!

But yeah, for version `0.7.1` of `pins-python`, there's a typo on line 305, `./pins/boards.py`. It looks like an "f" is missing at the beginning of the error message for the f-string and a comma is missing between the line break?

```
                raise PinsError(
                    "Attempting to write pin version to {dst_version_path}, "
                    "but that directory already exists."
                )
```

I got this error when I tried to run `pin_write` twice very quickly and since the hash is the same and the time difference between the two calls are two small the version became the same and the check probably tripped.

Sincerely,
EDIT: added relevant code chunk

**Comment by machow** [comment]
Thanks for reporting -- should be fixed in latest release!

https://github.com/rstudio/pins-python/releases/tag/v0.7.2
