### ISSUE TITLE
ImportError: cannot import name 'hash_name' from 'fsspec.implementations.cached'

### ISSUE THREAD

**Issue by dpprdan** [rstudio/pins-python#214]
In get an ImportError on `import pins` in a new conda environment. 

My environment.yml

```
name: pins_test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - s3fs
  - boto3
  - pins
  - ipykernel
```

On `import pins` I get a 

```
ImportError: cannot import name 'hash_name' from 'fsspec.implementations.cached' (c:\Users\Daniel\AppData\Local\mambaforge\envs\pins_test\Lib\site-packages\fsspec\implementations\cached.py)
```

`hash_name` is (supposed to be) imported here:
https://github.com/rstudio/pins-python/blob/ea242bc4c48ccd1e2cfbfc9d824e9935d4bb660c/pins/cache.py#L8

But [`fsspec/implementations/cached.py`](https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/cache_mapper.py) does not contain an importable `hash_name` function since [this commit](https://github.com/fsspec/filesystem_spec/commit/aacc5f2b80f44a19f8d9aeac30608ec5d9f406db#diff-f666a92a1998ffbca1fd88a9a7068512d06195fad9e845e707c7848835d31a5eL841-L846), AFAICT.

cf. https://community.rstudio.com/t/python-pins-will-not-run-in-shiny-for-python-app-on-posit-connect-server/173148

**Comment by dpprdan** [comment]
related to #212

It works now after rebuilding the environment, seems to have been a hickup in my conda env.

**Comment by isabelizimm** [comment]
Thank you for bringing up this concern, @dpprdan! 

You are correct, `fsspec`, an underlying dependencies in pins, changed how caching is handled very recently, so some versions are no longer compatible. You will run into this mismatch if you have `pins<0.8.3` and `fsspec>=2023.9.0`. We plan to fix the `fsspec` import error soon. For now, if that error pops up again, try updating to the latest version of pins, which will restrict installation to only compatible versions.

I'm glad you were able to fix this in your own environment, and will close out this issue as solved. Let me know if you run into any other problems!
