### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by PeterJCLaw** [rstudio/pins-python#225]
I was wondering when there might be another release of `pins`?

The currently released version depends on a fairly old version of `fsspec`, which unfortunately conflicts with the latest versions of other packages in the ML ecosystem -- in some cases making it hard for users to update to patch security issues. This issue seems to have been fixed on `main` (https://github.com/rstudio/pins-python/pull/221), though I don't know what your normal release cadence is.

**Comment by PeterJCLaw** [comment]
Looks like https://github.com/rstudio/pins-python/releases/tag/v0.8.4 is out, thanks!

**Comment by isabelizimm** [comment]
Thank you so much for the nudge 😄 Happy pinning!
