### ISSUE TITLE
Suggestions on faster caching

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/pins-python#234]
I am curious if you have any suggestions on how I could implement faster reading from the cache for Posit Connect pins. I was doing some testing and found that:

- For my dataset, `pin_read` took ~ 3 seconds to read from the cache.
- If I use `pd.read_parquet('path-to-cache/file.parquet')` the same file is read in ~ 33 ms.

I assume the overhead from `pin_read` has something to do with making an API call to Connect to get the meta data.

- Is this the expected performance?
- Can anything be done to speed up cache reads?

## Example

``` python
from pathlib import Path

import pandas as pd
import pins
from dotenv import load_dotenv

load_dotenv()
```

    True

``` python
board = pins.board_connect()
board
```

    <pins.boards.BoardRsConnect at 0x129282a20>

``` python
# Get the metadata
meta = board.pin_meta("sam.edwardes/vessel_history_clean")
```

``` python
path = (
    Path(
        "~",
        "Library/Caches/pins-py/rsc_799142d110b3ee9b1b200cf61cb0e1d90eeee15e49602f4545918457accd2d11/sam.edwardes+vessel_history_clean/",
        meta.version.version,
        meta.file
    )
    .expanduser()
)
path
```

    PosixPath('/Users/samedwardes/Library/Caches/pins-py/rsc_799142d110b3ee9b1b200cf61cb0e1d90eeee15e49602f4545918457accd2d11/sam.edwardes+vessel_history_clean/549885/vessel_history_clean.parquet')

``` python
# Delete the file from my computer so it is not in the cache.
path.unlink()
```

``` python
%time
# Download the data for the first time.
board.pin_read("sam.edwardes/vessel_history_clean")
```

    CPU times: user 1 μs, sys: 0 ns, total: 1 μs
    Wall time: 2.15 μs

<div>

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }
&#10;    .dataframe tbody tr th {
        vertical-align: top;
    }
&#10;    .dataframe thead th {
        text-align: right;
    }
</style>

|        | Vessel    | Departing     | Arriving      | ScheduledDepart           | ActualDepart              | EstArrival                | Date                      |
|--------|-----------|---------------|---------------|---------------------------|---------------------------|---------------------------|---------------------------|
| 0      | cathlamet | vashon island | fauntleroy    | 2020-01-01 13:40:00+00:00 | 2020-01-01 13:41:12+00:00 | 2020-01-01 13:57:07+00:00 | 2020-01-01 13:40:00+00:00 |
| 1      | cathlamet | fauntleroy    | vashon island | 2020-01-01 14:10:00+00:00 | 2020-01-01 14:11:37+00:00 | 2020-01-01 14:27:57+00:00 | 2020-01-01 14:10:00+00:00 |
| 2      | cathlamet | vashon island | fauntleroy    | 2020-01-01 14:35:00+00:00 | 2020-01-01 14:37:37+00:00 | 2020-01-01 14:49:19+00:00 | 2020-01-01 14:35:00+00:00 |
| 3      | cathlamet | fauntleroy    | vashon island | 2020-01-01 15:05:00+00:00 | 2020-01-01 15:07:11+00:00 | 2020-01-01 15:22:50+00:00 | 2020-01-01 15:05:00+00:00 |
| 4      | cathlamet | vashon island | southworth    | 2020-01-01 15:30:00+00:00 | 2020-01-01 15:31:01+00:00 | 2020-01-01 15:42:11+00:00 | 2020-01-01 15:30:00+00:00 |
| ...    | ...       | ...           | ...           | ...                       | ...                       | ...                       | ...                       |
| 520614 | yakima    | friday harbor | lopez island  | 2024-06-07 01:25:00+00:00 | 2024-06-07 01:58:45+00:00 | 2024-06-07 02:49:08+00:00 | 2024-06-07 01:25:00+00:00 |
| 520615 | yakima    | lopez island  | anacortes     | 2024-06-07 02:10:00+00:00 | 2024-06-07 02:59:00+00:00 | 2024-06-07 03:42:25+00:00 | 2024-06-07 02:10:00+00:00 |
| 520616 | yakima    | anacortes     | lopez island  | 2024-06-07 03:25:00+00:00 | 2024-06-07 04:03:25+00:00 | 2024-06-07 04:45:25+00:00 | 2024-06-07 03:25:00+00:00 |
| 520617 | yakima    | lopez island  | friday harbor | 2024-06-07 04:15:00+00:00 | 2024-06-07 04:53:21+00:00 | 2024-06-07 05:26:17+00:00 | 2024-06-07 04:15:00+00:00 |
| 520618 | yakima    | friday harbor | anacortes     | 2024-06-07 05:05:00+00:00 | 2024-06-07 05:36:37+00:00 | 2024-06-07 06:46:03+00:00 | 2024-06-07 05:05:00+00:00 |

<p>520619 rows × 7 columns</p>
</div>

</div>

``` python
%%timeit
# How long does it take to read the cached data?
board.pin_read("sam.edwardes/vessel_history_clean")
```

    3.02 s ± 112 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

``` python
%%timeit
# How long does it take to read the metadata?
board.pin_meta("sam.edwardes/vessel_history_clean")
```

    2.23 s ± 103 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

``` python
%%timeit
pd.read_parquet(path)
```

    32.1 ms ± 1.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

**Comment by machow** [comment]
Hey, thanks for digging into this--I think one big thing to be careful with up front is what pin read's job is:

* give you back the current version of a pin

Without any other information, this means two things are required:

1. It checks for the latest version of the pin
2. It reads that version (either by fetching the data, or loading from a cache)

You're right that reading a parquet file directly is faster, but it is skipping to step (2). I suspect there is room to optimize, though (there are redundant calls to connect, and additional overhead from converting from pin names to guids).

In case it's useful, you should be able to [stream the log](https://stackoverflow.com/a/53496263/1144523) for pins to stderr

```python
import logging

logging.basicConfig(format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    datefmt='%m-%d %H:%M')
logger = logging.getLogger("pins")
logger.setLevel(logging.INFO)

# then do any pins stuff
# it should print out calls to connect, etc..!
```

**Comment by SamEdwardes** [comment]
Thanks for taking a look at this Michael and explaining. I will take a look at the streaming suggestion.

**Comment by SamEdwardes** [comment]
@machow I'll mark this as closed. I do want to provide a bit more context on why this came up, though.

I am developing a shiny app right now. When the app starts, it reads in 3 pins from Connect. A start-up time of 3 seconds is okay to load one pin (even if cached), but when I have to load 3 pins, I am now waiting 9 seconds, even if all the data is cached. In situations like this, anything that could be done to speed up pin_read would be awesome!
