### ISSUE TITLE
Add `force_identical_write` arg

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#244]
This functionality was added to R pins in v1.2.0:

https://github.com/rstudio/pins-r/pull/735
https://github.com/rstudio/pins-r/issues/589

The same motivation applies; there is little value in re-writing an identical dataset, so it should be opt-in behaviour ideally.

**Comment by juliasilge** [comment]
I believe this is the same as #241. Good to get clarity that this is important to folks!

**Comment by nathanjmcdougall** [comment]
Ahh! That wasn't there last night... Apologies for the dupe.
