### ISSUE TITLE
Add `ruff` for development

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#251]
As a part of adding type annotations (#243), it might be useful to be aided by a linter that helps identify untyped functions.
An example of this is [`flake8-annotations`](https://pypi.org/project/flake8-annotations/) but I would like [`ruff`](https://github.com/astral-sh/ruff) to be considered instead, as a replacement for both `flake8` and `black`.

Besides being faster and a way to prevent tool proliferation, ruff is able to be configured from `pyproject.toml` (unlike `flake8`) which would support migration away from `setup.cfg` to `pyproject.toml` in the future.

A plan for enabling `ruff` would be as follows:

PR 1:
- Migrate black to the latest version in pre-commit config and deal with minor formatting changes (in my testing there would be 8 files with whitespace changes; deleted blank lines).

PR 2:
- Replacing `flake8` and `black` in the pre-commit config with `ruff` instead
- Configuring `ruff` with equivalent configuration to existing flake8 rules

**Comment by isabelizimm** [comment]
These would definitely be welcome changes! I've used `ruff` in other projects and have really enjoyed working with it. I think PRs 1/2 could be combined, but happy to accept in any configuration 😄
