### ISSUE TITLE
Migrate `setup.cfg` to `pyproject.toml`

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#271]
This is basically cosmetic, but I think it tends to make things easier to keep everything in one place:

- Reduces the total number of configuration files
- Removes the possibility of configuration duplication/conflicts between the two files

Only blocker is #251 since flake8 cannot be configured within `pyproject.toml`.

**Comment by isabelizimm** [comment]
Agreed 💯 the less config files the better!
