### ISSUE TITLE
Bugfix: off-by-one error in error message for version parsing

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#283]
Another nitpicky issue with these error messages:

https://github.com/rstudio/pins-python/blob/d215a8cd6cf958be0f4fc41c6e90e21c907b4655/pins/versions.py#L67-L73

If there is a malformed version `spam-eggs-spam`, this will emit
`version string can only have 1 '-', but contains 3`
Which is misleading, since there are only 2 hyphens, not 3.

While changing this, I think I'd prefer to use `try-except ValueError` around the unpacking of `parts` rather than have a dedicated `!= 2` check so that could be changed too.

**Comment by isabelizimm** [comment]
Ah, the off by one value error I can't unsee 🙈 I think the `!=2` is an okay check, is there a particular reason to make the swap to a `ValueError`?

**Comment by nathanjmcdougall** [comment]
It just avoids having to write an explicit check, but really it's a style/preference thing so I'll leave it be.
