### ISSUE TITLE
`BaseBoard.pin_versions_prune` deletes most recent version

### ISSUE THREAD

**Issue by LachlanMarnham** [rstudio/pins-python#297]
Hello. [The docstring](https://github.com/rstudio/pins-python/blob/cce839f0db1c710430af68ceffb8b3d940fb6ccf/pins/boards.py#L443) for `BaseBoard.pin_versions_prune` says that:

> Regardless of what values you set, `pin_versions_prune` will never delete the most recent version.

This works fine when one specifies some number of versions to keep (`n`), but fails when one specifies `days`. The code does indeed delete anything older than `days`, the problem is that it will also delete the most recent version, if it is older than `days`. I assume that the docstring is probably correct about the desired behavior here, but it could also be that the code is right and the docstring is wrong.

**Comment by isabelizimm** [comment]
Thank you for the report! It looks like there is a PR up, which I'll peek at to get a fix in 👍

**Comment by LachlanMarnham** [comment]
Thanks @isabelizimm
