### ISSUE TITLE
Reference to siuba in CI

### ISSUE THREAD

**Issue by nathanjmcdougall** [rstudio/pins-python#300]
https://github.com/rstudio/pins-python/blob/cce839f0db1c710430af68ceffb8b3d940fb6ccf/.github/workflows/ci.yml#L60

Is this an oversight when re-using the CI config? Might be worth correcting if so.

**Comment by isabelizimm** [comment]
Good eye! 🕵️ that _is_ the bucket we are using, although we do have an issue open to migrate to different accounts. Closing this in favor of the issue where that is tracked, #204
