### ISSUE TITLE
implement support for unversioned pins

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#31]
## Background

For full compatibilty with R pins, a user should be able to do the following:

* write for the first time an unversioned pin
* follow a process to switch a versioned pin to an unversioned one
  - e.g. receive an error, with instructions when multiple versions detected.
* set versioning defaults as a board level option
* specify a pin should be unversioned in pin_write

Relevant issues:

* https://github.com/machow/pins-python/issues/16

## Research needed

* Do we want to deviate from any of these behaviors?

**Comment by machow** [comment]
Note that R pins has pins_inform messages for creating / replacing of versions

**Comment by isabelizimm** [comment]
There are now unversioned pins with #211
