### ISSUE TITLE
Make sure there is a vetiver + pins demo to link to

### ISSUE THREAD

**Issue by machow** [rstudio/pins-python#41]
Whether it's more useful to navigate to a vetiver example folder, or to include one here so it's easy for people to grab while demo'ing pins.

**Comment by isabelizimm** [comment]
Happy to help on this! I have a scratch file of pins + vetiver working together; I can clean it up and add to https://github.com/isabelizimm/vetiverpydemo/ or elsewhere.

**Comment by isabelizimm** [comment]
vetiver has some pretty extensive examples on its docs, which I am guessing is where people will search for how to use vetiver + pins.
